name: Reusable workflow example

on:
  workflow_call:
    inputs:
      greet-who:
        required: true
        type: string
    outputs:
      greeting:
        value: ${{ jobs.greeting.outputs.greeting }}

jobs:
  greeting:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{ steps.greeting.outputs.greeting }}
    steps:
      - id: greeting
        run: echo "Hello ${{ inputs.greet-who }}! :coconut: " >> $GITHUB_STEP_SUMMARY
