name: Reusable workflow example

on:
  workflow_call:
    inputs:
      greet-who:
        required: true
        type: string

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello ${{ inputs.greet-who }}!" >> $GITHUB_OUTPUT
