name: Service Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  Plan:
    runs-on: ubuntu-latest
    container: node:18
   # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Show the files
        run: |
          pwd
          ls -al
      - name: Setup and run the script
        run: |
          npm install pg
          node ./bin/index.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432