name: GHA Test

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
      - uses: ./.github/templates/test-paths
        with:
          who-to-greet: 'Plan'
  Apply:
    runs-on: ubuntu-latest
    needs: [Plan]
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
      - uses: ./.github/templates/test-paths
        with:
          action-path: 'apply'
