name: GHA Test

on:
  push:
    branches:
      - master

permissions:
  actions: write
  id-token: write

jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
      - uses: ./.github/templates/test-paths
        with:
          who-to-greet: 'Plan'
          action-path: 'plan'
  Apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
      - uses: ./.github/templates/test-paths
        with:
          action-path: 'apply'
