name: GHA Test

on: [push]

jobs:
  This-Is-A-Test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.9"
    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Show Python version.
        run: python -V
